framework:
    cache:
        prefix_seed:            trusts
        app:                    cache.adapter.redis
#        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'
        default_redis_provider: '%env(REDIS_URL)%'
        #        app: cache.adapter.filesystem
        system:                 cache.adapter.system


          # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
          #app: cache.adapter.apcu
          
          # Namespaced pools use the above "app" backend by default
          #pools:
        #my.dedicated.cache: null