# config/packages/doctrine_mongodb.yaml
doctrine_mongodb:
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: { }
    default_database: '%env(MONGODB_DATABASE)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type:      annotation
                    dir:       '%kernel.project_dir%/src/Document'
                    prefix:    'App\Document'
                    alias:     App


#doctrine_mongodb:
#    auto_generate_proxy_classes: true
#    auto_generate_hydrator_classes: true
#    connections:
#        default:
#            server: '%env(resolve:MONGODB_URL)%'
#            options: {}
#    default_database: '%env(resolve:MONGODB_DB)%'
#    document_managers:
#        default:
#            auto_mapping: true
#            mappings:
#                App:
#                    is_bundle: false
#                    type: annotation
#                    dir: '%kernel.project_dir%/src/Document'
#                    prefix: 'App\Document'
#                    alias: App
#
#            metadata_cache_driver:
#                type: memcache
#                class: Doctrine\Common\Cache\MemcacheCache
#                host: localhost
#                port: 11211
#                instance_class: Memcache
#
#
when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes:    false
        auto_generate_hydrator_classes: false
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id:   doctrine_mongodb.system_cache_provider
    
    #    services:
    #        doctrine_mongodb.system_cache_provider:
    #            factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap']
    #            class: 'Doctrine\Common\Cache\Psr6\DoctrineProvider'
    #            public: false
    #            arguments:
    #                - '@doctrine_mongodb.system_cache_pool'
    
    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system